spring.datasource.url: jdbc:h2:file:./camunda-h2-database
maxWarriors: 100
camunda.bpm.admin-user:
  id: demo
  password: demo
camunda.bpm.default-serialization-format: application/json
url: https://randomuser.me/api/?inc=name&noinfo